### ISSUE TITLE
If test on copy number of mother volume slows down simulations

### ISSUE THREAD

**Issue by fzeiser** [fzeiser/OCL#17]
If test on the copy number of the mother volume in this line below slows down the computations a lot.
https://github.com/fzeiser/OCL/blob/478294cdbf68cad52955125838bf3812e4980848/SingleScint/src/SingleScintSteppingAction.cc#L51

Playing with the file a bit it seems as if it was not because of the actual selection of the copy number, but because of the if test.
However, we need some if test on the copy number in order to select the spectrum for a single detector / for each detector individually.

**Comment by fzeiser** [comment]
Another way to fix is the commit following afterwards, a659ab16be22621e195e1e16337ca85ebdda90c5, where no scintillation is simulated at all.

**Comment by grytveten** [comment]
I have anyhow rewritten so that we do not need if's in this part of the code.

**Comment by fzeiser** [comment]
As long as we have not merged in a659ab16be22621e195e1e16337ca85ebdda90c5, I would keep this open. (The corresponding commit is in a branch). I can also cherry-pick it in. -- It speeds up the simulations tremendously, so I think we should have scintillation deactivated by default.

**Comment by fzeiser** [comment]
Fixed in master
