### ISSUE TITLE
Warning: histogram 1 does not exist.

### ISSUE THREAD

**Issue by fzeiser** [fzeiser/OCL#18]
In the latest commit, b6b812d414bb120fa08be32ece2b7c2e955a2c31, I receive following warning message, when running the simulation
```
[...]
---> End of event: 7000
---> End of event: 8000
---> End of event: 9000
---> End of event: 10000
[...]
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : Analysis_W011
      issued by : G4THnManager::GetH1
      histogram 1 does not exist.
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------
```

Is that anything we can do something about?

**Comment by grytveten** [comment]
?Mystisk varsel. Jeg la ikke merke til den før. Så vidt jeg kan se skal det ikke være så mye som en eneste rest av noe histogram igjen i koden nå, men det er midt på natten og dagen har vært lang så jeg kan se på det igjen i morgen.

________________________________
