### ISSUE TITLE
InvalidRead issued by G4GDMLRead::Read() due to GDML schema  

### ISSUE THREAD

**Issue by fzeiser** [fzeiser/OCL#21]
I get following error when trying to use the CAD geometry files on `isotop`(not on my own machine):

```
[...]
coatingPlasticThickness: 3.55 mm
 ----> A OCLLaBr3 will be placed at distance: 16.3 cm
 ----> A OCLFrame will be placed at distance: (0,0,0) mm
Use Parallel World CAD Target Chamber: 1
G4GDML: Reading '../OCL/Mesh-Models/target_chamber.gdml'...

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : InvalidRead
      issued by : G4GDMLRead::Read()
ERROR - Empty document or unable to validate schema!
        Check Internet connection is ON in case of schema
        validation enabled and location defined as URL in
        the GDML file - ../OCL/Mesh-Models/target_chamber.gdml - being imported!
        Otherwise, verify GDML schema server is reachable!
*** Fatal Exception *** core dump ***
 **** Track information is not available at this moment
 **** Step information is not available at this moment

-------- EEEE -------- G4Exception-END --------- EEEE -------


*** G4Exception: Aborting execution ***
Aborted (core dumped)
-bash-4.2$ 
```

**Comment by fzeiser** [comment]
The corresponding section in `../OCL/Mesh-Models/target_chamber.gdml` is:

```
<?xml version="1.0" encoding="UTF-8" ?>
<gdml xmlns:gdml="../schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/gdml.xsd" >
<define>
<position name="center" x="0" y="0" z="0"/>
<rotation name="identity" x="0" y="0" z="0"/>
</define>
```

So I'll have to check what the `xmlns:xsi` thing stands for; I just copied/mixed together some information in this gdml files, so probably they are unceccesary.

**Comment by fzeiser** [comment]
It's probably another problem: the files are stored with `git lfs`, but the machine doesn't have git lfs. So there was a problem when reading the files: Just pointers were available locally.

**Comment by dortheg** [comment]
For documentation purposes: For me, this issue was fixed by first downloading & installing `git lfs` (described here: https://docs.github.com/en/github/managing-large-files/installing-git-large-file-storage) and then doing `git lfs pull` in the local OCL_GEANT4 repository. (Might be obvious for some, but it took me some Googeling, so thought I'd just post the solution)

**Comment by fzeiser** [comment]
Note that this is also specified under `0 - Dowloading notes` in the Readme. Or does your comment suggest that the Readme should be specified more clearly?
