### ISSUE TITLE
Range/Creation of Energy Spectrum

### ISSUE THREAD

**Issue by fzeiser** [fzeiser/OCL#5]
As mentioned in the commit 36266bb1f502411d95558e00d36efedc4906b6e0 I found the problem I've had with the Energy spectra before: They showed up very funny numbers, it looks like energy is not conserved. 
Partly, is seems that this is about the way there are created. In order to increase the range of your spectrum, youcannot simply increase the variables "ENumberChannel" and "ENumberChannel" (in the root file and) here:
https://github.com/fzeiser/OCL/blob/master/src/EventAction.cc#L22-L23

https://github.com/fzeiser/OCL/blob/36266bb1f502411d95558e00d36efedc4906b6e0/data/plotEnergyHist.C#L10-L11

I guess it would be helpful to have a look on how the spectra are saved
in the examples.

@grytveten @hirotakefurihata

**Comment by fzeiser** [comment]
I*m close to a solution, I hope you @grytveten  don't have to bother with it any more. I think I just have to do some re-naming. In any case already a spectrum is produced.

**Comment by fzeiser** [comment]
Works now, only needs some polishing!

In the command line we get an overview:

> EAbs : mean = 451.963 keV rms = 121.408 keV
> ... write Root file : ../data/Edep.root - done

and a root file is created, like this here, 100 events @5MeV
@grytveten: (how easy/difficult is it to merge/compare root files later? shall we rather export it as something else?)

![canvas_1](https://cloud.githubusercontent.com/assets/15156776/10619723/880b0f3c-7777-11e5-96ec-5a179bd262cb.png)

**Comment by grytveten** [comment]
Merging root files is rather easy and you can also add histograms easily.
Root is fine :)

But: I was wondering if we maybe should try to change it further so that the energy/bin remains constant? Would that be difficult?
It seems, from your attachment, that the binning is rather course when you go up to 5 MeV.

**Comment by fzeiser** [comment]
It was/ is in fact only a perculiarity of the way it's plotted here.
@grytveten  What binsize shall I chose?

**Comment by grytveten** [comment]
I guess 2 keV/bin should be fine. It is easy to reduce the number of bins (but not the other way around).

**Comment by fzeiser** [comment]
I think it makes sense to also switch the other two spectra we create to use the same method (directly to root), doesn't it?

Do you think it's necessary to write the spectra periodically to disk\* (say, every 10e6 events), or will it be ok to do this only at the end of the run?
- this was previously (in the Example I got) done in this obscure code 

``` javascript
void EventAction::fillThistogram(G4double T)
{
    G4double binT;
    G4int    iT;

    if(TNumberChannel > 0)
    {
        binT = (T/Trange)*((G4double) TNumberChannel);
        iT = 1 + (G4int) binT;
        if(iT > TNumberChannel-1) iT = TNumberChannel-1;
        if(iT < 0) iT = 0;
        Thistogram[iT] += 1.;
    }
}
```

**Comment by grytveten** [comment]
The only problem with only writing to disk at the end of the run is that if your code crashes you have to start from the beginning again. But writing takes a lot of time, so I think it is a good idea to just do it at the end of the run.

I guess it should not be a problem to use the same method (directly to root) for all spectra we generate and the code will probably be easier to read that way.

**Comment by hirotakefurihata** [comment]
The table so far.
There is also some blanks. I forgot execution or kept record.

I am not sure how should I change value(angular and event number)

I try light Japanese home cooking now.

2015-10-22 18:59 GMT+02:00 grytveten <notifications@github.com>:

**Comment by fzeiser** [comment]
@hirotakefurihata Can you upload/attach the table?

**Comment by hirotakefurihata** [comment]
I don't know how to upload to Github
https://drive.google.com/file/d/0B73cGJUTKhQ-YktKQzJLM01IUjA/view?usp=sharing



2015-10-23 12:25 GMT+02:00 fzeiser <notifications@github.com>:

**Comment by fzeiser** [comment]
What's the meaning of "column L" that is filled from "Row 30" and 
onwards? (or is it just a typo?)

**Comment by hirotakefurihata** [comment]
Not typo.
I can often see this peak around 500KEV when I set up energy more than 1MEV.
I think there is something physical meaning but I don't understand.
I need to check google, sorry.



2015-10-23 13:24 GMT+02:00 fzeiser <notifications@github.com>:

**Comment by grytveten** [comment]
Do you mean that in column L you have counted how many events there are in the 511 keV bin?

When the gamma energy is high, you start to see 511 keV events in the crystal coming from pair production in the collimator material.


- Gry

________________________________

**Comment by hirotakefurihata** [comment]
Yes, column L shows the event number around the 511KEV.
It means I checked the event of pair production in the collimator. I get it.


2015-10-23 14:55 GMT+02:00 grytveten <notifications@github.com>:

**Comment by hirotakefurihata** [comment]
I simulated with the collimator length 8cm.
In case of theta 160-180, the spectrum is similar for all energy except for
511KEV.
Then, I change the theta into theta 170-180. But now it takes much time to
execute.


2015-10-23 16:13 GMT+02:00 Hirotake Furihata <hirotakefu@gmail.com>:

**Comment by fzeiser** [comment]
I moved the discussion of results from here to #8 "Energy Spectrum: Results with Collimator length 2-4 MeV" to keep this issue on problems in the source code. Please post further issues on the results in #8!

**Comment by fzeiser** [comment]
They now all use the same method.
